# Generated by Django 3.0.1 on 2019-12-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=128, verbose_name='书名')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加图书日期')),
            ],
            options={
                'db_table': 'tb_book',
            },
        ),
    ]
